### ISSUE TITLE
When add an item into an array, which is bound to 'repeat' behavior, the '$parent' is undefined.

### ISSUE THREAD

**Issue by boogunote** [aurelia/templating-resources#27] opened 2015-03-11 14:55 UTC
`context.$parent = this.executionContext;` in `function updateExecutionContext()` should be moved to `function createBaseExecutionContext()` and `function createBaseExecutionKvpContext()`.

**Comment by EisenbergEffect** [comment] 2015-03-11 14:59
@martingust Can you look into this issue please? Let me know what you find and what you think we should do. Thanks!

**Comment by boogunote** [comment] 2015-03-11 15:00
@EisenbergEffect , I have fix it. Could I push the PR? I already signed your agreement.

**Comment by EisenbergEffect** [comment] 2015-03-11 15:02
Feel free to go ahead and send the PR. I'll have @martingust review it since he's familiar with that code and then if it all looks good I can merge and get it in for our next release.

**Comment by martingust** [comment] 2015-03-11 21:01
@boogunote Can you please provide some more info on how to reproduce this? I'm not able to.

**Comment by boogunote** [comment] 2015-03-12 03:22
@martingust , Please checkout 
`https://github.com/boogunote/bn5/blob/master/src/tree-node.js` and 
`https://github.com/boogunote/bn5/blob/master/src/tree-node.html`.

I initialize view model in Ln.5 of tree-node.html.
```
  <section repeat.for="child of node.children">
    <compose
      model.bind="{'node':child, 'parentVM':$parent}"
      view-model="tree-node">
    </compose>
  </section>
```
Add check the model in `activate()` at Ln. 14 of tree-node.js.
```
  activate(model){
    console.log("TreeNode activate");
    console.log(model)
    this.node = model.node;
    this.parentVM = model.parentVM;
    this.treeVM = model.parentVM.treeVM;
  }
```


In the first round, everything work will. When `children` bind to `repeat`, I can access corrent `$parent` by `model.parentVM` in `activate()`.

But when I add an item to `children` programmatically, by `addChild() `, I check `model.parentVM` in `activate()` again and see it's `undefined`.

**Comment by martingust** [comment] 2015-03-12 10:39
Thank you. I have got it reproduced and confirmed your fix works. Will let Rob know.

**Comment by martingust** [comment] 2015-03-16 05:38
@EisenbergEffect We can go ahead and close this.

**Closed** 2015-03-17 06:10 UTC
