### ISSUE TITLE
Memory leak with slot > repeat

### ISSUE THREAD

**Issue by zakjan** [aurelia/templating-resources#310] opened 2017-10-01 16:21 UTC
**I'm submitting a bug report**

* **Library Version:**
1.4.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Browser:**
Chrome 62.0.3202.29

**Current behavior:**
When repeat.for is used in slot content, updating the iterated collection causes memory leaks. It doesn't release unused custom elements from previous collection items.
```
  <container>
    <template repeat.for="item of items">
      <item item.bind="item"></item>
    </template>
  </container>
```

Steps to reproduce:
1) open https://gist.run/?id=5c2d55c58bb270bfab2f41026898cd23
2) take a heap snapshot, filter objects by Item -> found 5x
3) click Reset items button
4) force GC
5) take a heap snapshot, filter objects by Item -> found 10x

**Expected/desired behavior:**
* **What is the expected behavior?**
All custom elements should be GC'ed when not displayed. Step 3) should return 5 Item objects only.

* **What is the motivation / use case for changing the behavior?**
Prevent memory leaks in long-running SPA when the iterated collection changes.

**Comment by zakjan** [comment] 2017-10-01 19:02
Probably related to #265.

**Comment by andlebed** [comment] 2018-04-05 11:16
I also noticed that all lifecycle hooks are triggered except **unbind**.

**Comment by bigopon** [comment] 2018-06-20 08:37
@EisenbergEffect Fixed by aurelia/templating#592

**Comment by rbakhshi** [comment] 2018-07-20 11:44
That commit didn't fix this problem. But the workaround works fine

**Comment by hdplampert** [comment] 2018-09-28 16:53
Another reproduction here:
https://gist.run/?id=2626ec6901e7876c586edada483e4f99
Click on Add, then Remove. Take a heap snapshot after forcing garbage collection. Look for objects with constructor Item.

It looks like ShadowSlot is keeping references to it's children but never disposing of them.
Removing those references on `ShadowSlot.removeView` appears to solve the leak, but I'm not sure if it is the correct approach.

**Comment by bigopon** [comment] 2018-09-29 04:57
@hdplampert I don't think the gist is running on latest version of Aurelia. Can you try again with this https://codesandbox.io/s/9zzq38mn94

**Comment by bigopon** [comment] 2019-03-21 13:16
Fixed by https://github.com/aurelia/templating/pull/637

Please help file new issue if the problem still persists for you.

**Closed by bigopon** 2019-03-21 13:16 UTC

**Comment by thomas-darling** [comment] 2020-01-18 04:54
@EisenbergEffect @bigopon
This bug is still very much still alive! 🐛

I've opened a new issue here: https://github.com/aurelia/templating-resources/issues/392
