### ISSUE TITLE
When using an array indexer in a binding, repeat doesn't correctly set the bindingContext.

### ISSUE THREAD

**Issue by Azim-Palmer** [aurelia/templating-resources#113] opened 2015-10-02 11:17 UTC
If I write this:

`<div repeat.for="dataItem of testData[0]"> 
  using dataItem : ${dataItem}
  using item : ${item}
`  </div>

Then dataItem will not display anything, BUT item will, this is because in repeat.js this.local gets set to ‘item’ and when the binding expression contains an indexer it’s not setting binding name somewhere in the binding chain.

I verified this by replacing this.local with an Object.defineProperty and confirming that it’s not set when the binding contains an array indexer, which is why if you add a view-spy to the div you can see an item in the context.

Created a repro example here : https://github.com/Azim-Palmer/skeleton-navigation

**Comment by EisenbergEffect** [comment] 2015-10-02 12:05
@martingust Can you take a look at this?

**Comment by jdanyow** [comment] 2015-10-02 14:26
duplicate of https://github.com/aurelia/templating-resources/issues/100

**Closed by jdanyow** 2015-10-02 14:26 UTC
