### ISSUE TITLE
Compose bindings without initial view-model hangs the application.

### ISSUE THREAD

**Issue by Souldrinker** [aurelia/templating-resources#194] opened 2016-03-02 14:37 UTC
Not sure if it's a bug or an intentional breaking change related to the new ```CompositionTransaction``` that I missed in the blog post, but it seems like the attached method never gets called in the latest Aurelia release if I have compose bindings whose ```view-model.bind``` is null when leaving the activate method.

In some cases in my application I don't know which view to load until the dom is attached and leave it as null until attached is called. This worked before, but with the latest release attached never gets called in this case and I don't get any errors (just an empty dom). If I add an if-bind like ```<compose if.bind="theView" model.bind="someId" view-model.bind="theView"></compose>``` it works, so I got stuff working again, but was a bit curious if this is by design or a bug since it was a bit confusing why nothing happened and took a bit of debugging finding out how to get around it.

**Comment by EisenbergEffect** [comment] 2016-03-02 14:52
It sounds like an accidental regression since we probably hadn't accounted for that particular use case. Can you create a simple app, based on the nav skele, that reproduces the problem? If you can, I can probably get a fix out today, maybe within an hour or so. It all depends on having that repro.

**Comment by Souldrinker** [comment] 2016-03-02 15:30
I'm not used to push things to github, but I think I managed to create a repro based on the latest es2016 skeleton here: https://github.com/Souldrinker/compose-issue-194

I added a compose binding at the bottom of welcome.html which I bind to a property in my vm that is null initially and gets set in attached. In previous versions of Aurelia this worked just fine, but now the app never gets loaded and attached is never called.

**Comment by EisenbergEffect** [comment] 2016-03-02 15:37
I'll look at it shortly. Thank you.

**Comment by EisenbergEffect** [comment] 2016-03-04 02:10
Sorry this got delayed. I'll be looking at it next.

**Comment by EisenbergEffect** [comment] 2016-03-04 06:38
Should be fixed in the latest release. Try running `jspm update`.

**Closed by EisenbergEffect** 2016-03-04 06:38 UTC

**Comment by Souldrinker** [comment] 2016-03-04 11:56
Yes, it's working fine now again also when I removed the if.binds, thanks :-)
