### ISSUE TITLE
Two way binding in inner-html

### ISSUE THREAD

**Issue by zewa666** [aurelia/templating-resources#24] opened 2015-03-01 11:46 UTC
The inner-html attachedBehavior currently doesn't support two-way bindings.
Here is an example:

```
<div class="col-md-2">
      <table class="table">
      <thead>
      <tr>
        <th>Col1</th>
        <th>Col2</th>
      </tr>
      </thead>
      <tr>
        <td contenteditable="true" inner-html="value.two-way: tdtext;"></td>
        <td>Static text</td>
      </tr>
    </table>
      <input type="text" value.bind="tdtext" />
</div>
```

**Comment by jdanyow** [comment] 2015-03-01 12:04
this is a duplicate of https://github.com/aurelia/binding/issues/45

**Comment by zewa666** [comment] 2015-03-01 12:11
Here is a proposal ... how about attaching to the input event which is fired by the contenteditable like this:

```
constructor(element){
    this.element = element;
    this.sanitizer = InnerHTML.defaultSanitizer;

    if(this.element.hasAttribute('contenteditable')) {
      this.element.addEventListener('input', (ev) => {
        this.value = this.sanitizer(ev.target.innerHTML);
      });
    }
}
```

**Comment by EisenbergEffect** [comment] 2015-03-17 05:58
In master.

**Closed by EisenbergEffect** 2015-03-17 05:58 UTC
Labels: enhancement
