### ISSUE TITLE
Aurelia if custom attribute does not work if it's rebound

### ISSUE THREAD

**Issue by zenorbi** [aurelia/templating-resources#315] opened 2017-10-03 10:06 UTC
**I'm submitting a bug report**

* **Library Version:**
1.5.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13

* **Node Version:**
v8.6.0

* **NPM Version:**
5.3.0

* **JSPM OR Webpack AND Version**
aurelia-cli 0.31.3

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
Rebinding a view having an if custom-attribute does not rebind the subviews inside the if.

**Expected/desired behavior:**

* **What is the expected behavior?**
Here is a repo to reproduce the bug as the gist.run does not use the latest `aurelia-templating-resources`.
https://github.com/zenorbi/aurelia-if-bug
Here is the gist with a the older aurelia-templating-resources which works: https://gist.run/?id=ef8b6fb22488bafda3c15b975e9c1820

**Comment by bigopon** [comment] 2017-10-03 10:57
What browser did you get the wrong behavior ? It's working fine for me, the button is doing its job properly. Did you miss anything in bug reproduction instruction ?

**Comment by zenorbi** [comment] 2017-10-03 11:00
@bigopon Chrome Version 61.0.3163.100 (Official Build) (64-bit) also using Firefox 56.0 (64-bit)

Please make sure you use the repo I linked as the gist version uses an older `aurelia-templating-resources`.

**Comment by bigopon** [comment] 2017-10-03 13:34
Only happen to nested `if`. The `View` of nested `if` will not call `bind` for some reason

**Comment by zenorbi** [comment] 2017-10-03 19:47
Well not just in case of nested `if`s, but any `if` binding where you `unbind` then `bind` the view again which has an `if` attribute somewhere inside it. The outside `if` is just the simplest way to get a view then unbind and rebind it.
In our internal project we use a caching aurelia `ViewFactory` where the created view only has a single `if` binding but due to caching we reuse thus rebind the view multiple times.

**Comment by nenadvicentic** [comment] 2017-10-10 11:08
Same problem here.
After template is hidden and shown again, `delegate` binding on some items does not work any more.

```
<template if.bind="...">
    <button if.bind="..." click.delegate="doSomething()"></button>
</template>
```

**Comment by jods4** [comment] 2017-10-18 01:19
#317 is a duplicate of this but contains an analysis of the cause and a proposed solution in a comment.

@EisenbergEffect We can close this issue and track the problem with #317.

**Comment by EisenbergEffect** [comment] 2017-10-19 03:55
Closing as duplicate of an issue that we've merged the fix for. See #317

**Closed by EisenbergEffect** 2017-10-19 03:55 UTC
