### ISSUE TITLE
repeat.for + animations still not production ready, view can desync with array leading to duplicates and loss of order.

### ISSUE THREAD

**Issue by ohjames** [aurelia/templating-resources#183] opened 2016-02-03 12:39 UTC
After my fixes in the animator (https://github.com/aurelia/animator-css/issues/35 and https://github.com/aurelia/animator-css/pull/33) and my fix in this project (#167) I was hoping to see the last of issues this critical but the combination of `repeat.for` and `au-animate` still leads to duplicate entries in the view, the view entries not being sorted correctly and items missing from the end of the repetition.

I've noticed this issue many times over the last few weeks, I can't replicate it reliably in a test though, must be the result of a race condition.

If I add the elements `['a'..'z']` using only splices (but say, adding 'a', 'b', 'z'; then splicing in 'c', 'd', 'e' and so on until I have all 26 elements) rather than seeing 26 elements in order from 'a' to 'z' I *will* see 26 elements. However I end up with the order like `['a', 'b', 'c', 'a', 'b', 'd', 'e', 'f', 'e' ... 'v']` (and elements after 'v' will be missing, the faulty duplicates "push them off the end") 

I see the issue when doing only inserts after about 10-20% of updates, so I started throttling updates so they only occur every 1 second, this makes the issue occur less frequently but it still happens enough to be annoying. It seems to happen in mobile chrome more than desktop chrome/firefox, perhaps the race condition shows up more frequently on machines with less CPUs.

You can see the issue on this website also: http://kchomp.co you'll need to add a few subscriptions for it to trigger.

I really would advise in the documentation for aurelia that animations + repeat.for are not ready yet also, I think this bug will take a while to track down and until then I wouldn't want other people relying on basic functionality that is critically broken.

**Comment by EisenbergEffect** [comment] 2016-02-03 13:38
@jdanyow @martingust I think this is a top priority issue. We need to get this sorted as quickly as possible. The bug could be present in a number of possible places, repeat.for, ViewSlot or the css animator. @joelcoxokc had some improvements to the css animator a while back but I'm not sure if they fixed this or other bugs or were just internal improvements. Can you guys take a look at this together?

**Comment by ohjames** [comment] 2016-02-03 13:48
I'm pretty sure the issue occurs when inserting new elements to an array during the view animation for a previous insert.

I can trigger the issue with:
 * Storing the updates in `nextArray` and running `array.splice(0, array.length, ...nextArray)` whenever `nextArray` changes.
 * Splicing the `array` directly.

**Comment by ohjames** [comment] 2016-02-03 13:53
@EisenbergEffect the only recent changes to `animator-css` are my fixes for other race conditions that led to consequences similar to this (much more frequently than they happen now).

The changes (or rather the rewrite) by @joelcoxokc are in [this open PR](https://github.com/aurelia/animator-css/pull/37).

His approach to timing the animations is the same as the one I implemented in the previous code though, I don't believe they will fix this issue.

**Comment by ohjames** [comment] 2016-02-29 12:03
I'd like to stress again how significant this bug is, `repeat.for` *only works* if you wait `2 * animation-duration` between updates. I really hope Aurelia 1 doesn't release with this issue because:
 * It's super easy to trigger it.
 * The results are catastrophic.

**Comment by martingust** [comment] 2016-02-29 12:59
@ohjames Could you please provide an (as simple as possible) example of how to reproduce this?

**Comment by ohjames** [comment] 2016-02-29 13:15
I've been meaning to add a test to this repository but I've had very little time, you can trigger it fairly easily though by:
1. Having some repeated items with a `repeat.for` and an animation duration of 1000ms.
2. Keep inserting elements into the array with less than a `1000ms` gap between inserts, make sure some of the inserts are to the middle of the array, some are to the head and some are to the end.

You can also trigger it by building up the list with a new array each time, e.g.:

```javascript
setTimeout(() => array.splice(0, array.length, 'a', 'd', 'g'), 200)
setTimeout(() => array.splice(0, array.length, 'a', 'b', 'c', 'd', 'h'), 800)
setTimeout(() => array.splice(0, array.length, 'a',  'b', 'c', 'd', 'e', 'f', 'g', 'h'), 1200)
```
That series of inserts may or may not lead to the bug. I'm not sure of the sequence that triggers it. In all the cases I've tested deletions have only been at the end of the array.

**Comment by martingust** [comment] 2016-02-29 18:06
@ohjames “Unfortunately” that did not cause any issues for me. I’ll try tinker with it to see if I can trigger some unexpected behaviour. If you could provide an example that would help a lot, does not need to be a unit test (seems like this will be hard to reproduce in a unit test).

**Comment by EisenbergEffect** [comment] 2016-02-29 18:17
@ohjames We would like to get this fixed with the highest of priorities. If you can re-create the problem in a simplest possible aurelia app so we can just drop it in the skeleton and see things go wrong, that would greatly help us get to the bottom of this. Thanks!

**Comment by ohjames** [comment] 2016-03-01 11:36
![desync](https://cloud.githubusercontent.com/assets/97685/13425885/c2d49e16-dfa1-11e5-840a-a3b2c4ff1a34.png)

**Comment by atsu85** [comment] 2016-03-01 11:45
@ohjames, I tried your link with Sony Xperia Z1 compact, and didn't see any problems. Could this problem be related to BrowserSync (or how it is configured)?

**Comment by ohjames** [comment] 2016-03-01 11:50
The issue is definitely not related to browsersync. You are very lucky the issue didn't manifest, I see it after 99% of reloads on my desktop PC. On my Moto E it happens 100% of the time and with greater desync. 100s of our users have also reported the issue. If you reload a few times you'll definitely see it, make sure to closely observe the point scores.

**Comment by martingust** [comment] 2016-03-01 13:05
@ohjames In Chrome on Mac I see all rows ordered by score overtime. However in Chrome on iPad I can see rows not ordered by points. There is really hard to see what is going on in the code though since it's all bundled and mangled JavaScript. Is there any chance you could provide the simplest possible code to replicate this? As @EisenbergEffect said we need to be able to drop this into skeleton to be able to fix it.

**Comment by joelcoxokc** [comment] 2016-03-01 16:46
@EisenbergEffect. Could this possibly be related to using
`viewSlot.removeAll()`. If you add anything in the array before the
returned promise resolves... You get issues.

Maybe go throw the viewSlot. And any time `removeAll` is invoked, create a
direct copy of the children's array. And set children to []. Then let
removeAll iterate through an old collection... One that cannot be pushed to
anymore.

There is a setTimeout inside the animator. Even when there are no
animations, if something is removed... It won't happen till after the
timeouts. Maybe if we go ahead and remove the view from the viewSlots
children first... The pass it to the animator. This could potentially work.

**Comment by ohjames** [comment] 2016-03-01 20:05
I tried adding a test in `array-repeat-strategy.spec.js` but I need to write a function that will `arrayDiff(src, dest)` and return a list of splices otherwise the test will be unreadable and a tonne of hassle to write. May just go for a fork of aurelia-skeleton and reproduce it that way then, it's pretty easy to replicate so it shouldn't be too much trouble, even with a broken arm ;)

**Comment by ohjames** [comment] 2016-03-02 00:50
There committed a version of the skeleton app that demonstrates the issue:

https://github.com/ohjames/skeleton-navigation
https://github.com/ohjames/skeleton-navigation/commit/32be189bbc354358437ed7197064f5c5c1310135

Uploading an image where you can see "C2" and "E1" gets duplicated and end up overwriting the elements in the positions they should be. The console is open in the screenshot to show the array has the correct order of elements.

![issue](https://cloud.githubusercontent.com/assets/97685/13447087/b2dc13da-e010-11e5-832c-30420e3b7e09.png)

**Comment by ohjames** [comment] 2016-03-02 00:58
Hosting a copy of this code here so you can check it out: http://chilon.net:9123/#/users

With the given timing the duplicates/overwrites seem to manifest in the same way every time in both firefox and chrome for me.

**Comment by ohjames** [comment] 2016-03-02 00:58
f

**Comment by ohjames** [comment] 2016-03-02 01:23
Sorry my cat closed the issue. I've made another commit to make the test even smaller. Now the array contains `A, B, C` but the view shows `A, B, B`. I think performing an update while an existing animation is hiding something triggers the bug.

**Comment by EisenbergEffect** [comment] 2016-03-02 02:16
Thanks for recreating the problem @ohjames 
@martingust Can you take it from here?

**Comment by martingust** [comment] 2016-03-02 18:52
Thanks @ohjames! @EisenbergEffect yes, took a quick look and definitely something going wrong when the splices are [queued](https://github.com/aurelia/templating-resources/blob/master/src/array-repeat-strategy.js#L107).

**Comment by martingust** [comment] 2016-03-03 16:30
The issue happens when a second set of changes manipulates the array before the first set of changes has reached [here](https://github.com/aurelia/templating-resources/blob/master/src/array-repeat-strategy.js#L190), resulting in the array being out of sync and view could be created with wrong data. Passing in a copy of the array [here](https://github.com/aurelia/templating-resources/blob/6445cfb09c4d6d2856a411d2af36431ab47a1ff2/src/array-repeat-strategy.js#L116) solves the issue.

I could not very easily create a reliable unit test for this but it is tested in @ohjames skeleton clone and with a couple other scenarios and all current tests pass. There could potentially be more problems, @ohjames would you mind test this change and see how it works for you and let me know if you find more issues related to this. 

cc @EisenbergEffect

**Comment by ohjames** [comment] 2016-03-03 16:52
@martingust That seems to have fixed it! So happy about this! Would be great if you could apply it to the master branch and include it in a release asap!

**Comment by martingust** [comment] 2016-03-03 17:04
Glad it fixed it. I'll get with @EisenbergEffect on a release as soon as possible.

**Closed** 2016-03-04 01:59 UTC
Labels: bug

**Comment by EisenbergEffect** [comment] 2016-03-04 02:03
@ohjames Released!
