### ISSUE TITLE
Chrome warning: /deep/ combinator is deprecated

### ISSUE THREAD

**Issue by mhoyer** [aurelia/templating-resources#135] opened 2015-11-02 22:16 UTC
### The issue

I just updated [Aurelia - TodoMVC](https://github.com/mhoyer/todomvc-aurelia) to latest packages and structure of [skeleton-navigation](https://github.com/aurelia/skeleton-navigation).

But, when running the app in Chrome 46 I see this warning in console:

    /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

This was already mentioned in [Gitter](https://gitter.im/Aurelia/Discuss?at=561d8bef0376066b0f8c8696).

### Quick fix

I was able to fix it locally by removing the ```/deep/``` from here https://github.com/aurelia/templating-resources/blob/00e639/src/aurelia-templating-resources.js#L24

### See also
- https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/68qSZM5QMRQ/pT2YCqZSomAJ
- https://drafts.csswg.org/css-scoping/#deep-combinator

**Comment by EisenbergEffect** [comment] 2015-11-02 22:24
It will get fixed in the future when we implement ShadowDOM v1. It's not a bug though, it's just a feature that is going away in Chrome in the near future.

**Closed by EisenbergEffect** 2015-11-02 22:24 UTC
