### ISSUE TITLE
Error loading css with webpack

### ISSUE THREAD

**Issue by dstroyrofworlds** [aurelia/templating-resources#249] opened 2016-08-22 11:35 UTC
**I'm submitting a bug report**
- **Library Version:**
  1.0.0
- **Operating System:**
  Windows 7
- **Node Version:**
  6.1.0
- **NPM Version:**
  3.10.3
- **JSPM OR Webpack AND Version**
  webpack 2.1.0-beta.21
- **Browser:**
  Chrome 52
- **Language:**
  TypeScript 1.9.0-dev || 2.0.0

**Current behavior:**
![aurelia](https://cloud.githubusercontent.com/assets/5618989/17853389/7d5d3fe2-686c-11e6-94e2-05b431aa1a8e.PNG)

I get this error loading css. The function checks if it is a string, but it is an empty object.

```
Unhandled rejection Error: Failed loading required CSS file: nm-semantic-ui/dist/button.css
    at fixupCSSUrls (http://localhost:9000/aurelia.bundle.js:6538:11)
    at http://localhost:9000/aurelia.bundle.js:6577:14
From previous event:
    at CSSResource.load (http://localhost:9000/aurelia.bundle.js:6576:8)
    at ResourceDescription.load (http://localhost:9000/aurelia.bundle.js:14675:26)
    at ResourceModule.load (http://localhost:9000/aurelia.bundle.js:14624:35)
    at http://localhost:9000/aurelia.bundle.js:14985:41
From previous event:
```
- **What is the expected behavior?**

I expect the stylesheet to load.

My project consists of several smaller node projects. Each uses the same setup and configuration.
All the smaller projects works and loads the CSS.

I am using the webpack setup from the skeleton project.

**Comment by dstroyrofworlds** [comment] 2016-08-22 11:41
Updating the function

```javascript
function fixupCSSUrls(address, css) {
  if (typeof css !== 'string') {
    throw new Error('Failed loading required CSS file: ' + address);
  }
  return css.replace(cssUrlMatcher, function (match, p1) {
    var quote = p1.charAt(0);
    if (quote === '\'' || quote === '"') {
      p1 = p1.substr(1, p1.length - 2);
    }
    return 'url(\'' + (0, _aureliaPath.relativeToFile)(p1, address) + '\')';
  });
}
```

to

```javacript
function fixupCSSUrls(address, css) {
  if (typeof css !== 'string') {
    //throw new Error('Failed loading required CSS file: ' + address);
      return '';
  }
  return css.replace(cssUrlMatcher, function (match, p1) {
    var quote = p1.charAt(0);
    if (quote === '\'' || quote === '"') {
      p1 = p1.substr(1, p1.length - 2);
    }
    return 'url(\'' + (0, _aureliaPath.relativeToFile)(p1, address) + '\')';
  });
}
```


works - there do not seem to be any errors and the CSS is loaded.

The config in webpack for the CSS is :
```javascript
require('@easy-webpack/config-css')
            ({filename: 'styles.css', allChunks: !!ELECTRON, sourceMap: false}),
```

The CSS is loaded in the styles.css file and some are included in the page as style elements.

**Comment by jdanyow** [comment] 2016-09-02 02:07
@niieani - was this fixed recently? Thought I saw a similar issue in the queue not too long ago.

**Comment by niieani** [comment] 2016-09-02 11:36
Odd. The real question is why is the `css` variable an empty Object? 
@dstroyrofworlds could you make a simple repo which reproduces the issue?

**Comment by dstroyrofworlds** [comment] 2016-09-05 11:44
@niieani I'll try to make a repo - as soon as I have time.

**Comment by JayDi85** [comment] 2016-09-15 17:50
I have the same error with standard contacts app from tutorial with nprogress element.

Got it when update bootstrap to 4.0.0-alpha.4 version:
`Failed loading required CSS file: nprogress/nprogress.css`

Fix it by change loading sequence in aurelia.json file.

From:
```
          "jquery",
          {
            "name": "bootstrap",
            "path": "../node_modules/bootstrap/dist",
            "main": "js/bootstrap.min",
            "deps": ["jquery"],
            "exports": "$",
            "resources": [
              "css/bootstrap.css"
            ]
          },
          {
            "name": "nprogress",
            "path": "../node_modules/nprogress",
            "main": "nprogress",
            "resources": [
              "nprogress.css"
            ]
          }
```

to
```

          "jquery",
          {
            "name": "nprogress",
            "path": "../node_modules/nprogress",
            "main": "nprogress",
            "resources": [
              "nprogress.css"
            ]
          },
          {
            "name": "bootstrap",
            "path": "../node_modules/bootstrap/dist",
            "main": "js/bootstrap.min",
            "deps": ["jquery"],
            "exports": "$",
            "resources": [
              "css/bootstrap.css"
            ]
          }
```

Don't know why, but it work for me.

**Comment by niieani** [comment] 2016-09-16 09:24
@JayDi85 the `aurelia.json` isn't used with Webpack builds at this time. Perhaps your problem was in fact different?

**Comment by JayDi85** [comment] 2016-09-16 09:31
@niieani yes, it's not webpack. I'm using aurelia-cli and got same error with loading css-resources.

**Comment by EisenbergEffect** [comment] 2016-10-03 05:11
Is this still an issue with the latest libs and cli?

**Comment by JayDi85** [comment] 2016-10-03 05:47
It's a very weird bug (sometimes new dependency with css-resources in `aurelia.json` could cause that error: timeout on css-text load function). 

Yesterday I'm manually update files in `\scripts` folder (`text.js` from 2.0.14 to 2.0.15 and `require.js` from 2.2.0 to 2.3.2). Now it's work fine. Maybe later that bug will be raise again.

**Comment by JayDi85** [comment] 2016-10-04 15:50
Firefox console show: "TypeError: plugin.load is not a function" when aurelia attempt load css-resources (that's why error "Failed loading required CSS file" raise).

After some research I [found that SO post about that error](http://stackoverflow.com/questions/39399772/unhandled-rejection-error-load-timeout-for-modules-template-registry-entry).

Author found solution in comments to first post:
28 Jul, to dynamically require text requires setting stub:false in the text plugin at aurelia.json > build.loader.plugins.

After change `stub` value to `false` in `aurelia.json` -- work fine for me. Bug is gone and app work correct.

**Comment by nmocruz** [comment] 2017-02-01 10:15
I was getting this error yesterday.  Using the yo generator-aspnetcore-spa, and then upgrade all libraries to use the webpack plugin 2.0 (with hmr) I got this problem.
There's `<require from="./app.css"></require>` that is a folder app\components\app\app.css, is doing the same thing.

**Comment by niieani** [comment] 2017-02-01 21:47
@nmocruz this will happen when your webpack configuration is incorrect, i.e. the `css` loader rules do not check for `issuer`. The yeoman generator is not updated for the webpack-plugin 2.0, thus the webpack.config file will not work with your setup.

**Comment by nmocruz** [comment] 2017-02-01 22:22
@niieani you can be right,  but I made an update to webpack, and other libraries, I'm trying to run the project without .net. using, but webpack-dev-server.

```
 module: {
        rules: [
            { test: /\.ts$/i, include: /ClientApp/, use: ['ts-loader']},
            { test: /\.html$/i, use: 'html-loader' },
            { test: /\.css$/i, use: [ 'style-loader', 'css-loader' ] },
            { test: /\.json$/i, use: 'json-loader' }
        ]
    },

```

and runing webpack-dev-server --hot

**Comment by niieani** [comment] 2017-02-05 16:23
try replacing the rule for `css` with these two, in this order:

```ts
      {
        // CSS required in JS/TS files should use the style-loader that auto-injects it into the website
        test: /\.css$/i,
        use: ['style-loader'],
        issuer: {
          // only when the issuer is a .js/.ts file, so the loaders are not applied inside templates
          test: /\.[tj]s$/i,
        },
      },
      {
        // CSS anywhere should use the css-loader
        test: /\.css$/i,
        use: ['css-loader'],
      },
```

Full new config [here](https://github.com/aurelia/skeleton-navigation/blob/webpack-experimental/skeleton-typescript-webpack-experimental/webpack.config.ts#L147-L164).

**Comment by niieani** [comment] 2017-02-05 16:25
@EisenbergEffect we can close this. Not a bug, just misconfiguration for the new webpack stack. It might make sense to add this into the docs once the new Webpack stack is released.

**Comment by jdanyow** [comment] 2017-02-05 18:21
Closing per @niieani ^^^

**Closed by jdanyow** 2017-02-05 18:21 UTC
Labels: bug

**Comment by iiiyx** [comment] 2018-04-25 13:12
@niieani Please advise any approach how we can debug styles (CSS or SASS) required from the templates. You just denied extracting them.
```
        // CSS required in templates cannot be extracted safely
        // because Aurelia would try to require it again in runtime
```
