### ISSUE TITLE
if bindingContext null in case the element is rendered for the second time

### ISSUE THREAD

**Issue by reinholdk** [aurelia/templating-resources#117] opened 2015-10-15 07:39 UTC
Hi,

seems to be a regression of version  0.16.0.
An element which is conditionally attached using if.bind runs into the following exception when rendered for the second time:
Uncaught TypeError: Cannot read property '__observers__' of nullgetObserver @ aurelia-binding.js:3946observeProperty 

Here is a small example to reproduce - just try to make <first> visible twice using the 'Toggle' button:

```html
<template>
  <require from="./test1"></require>
  <second></second>
</template>
```
```javascript
// test1.js
import {customElement, bindable, inlineView} from 'aurelia-framework';

@customElement('first')
@inlineView('<template><div>${foo.value}</div></template>')
export class First {
  
  @bindable foo;
  constructor() {
  }
}

@customElement('second')
@inlineView('<template><button click.delegate="toggle()">Toggle</button><first if.bind="visible" view-cache="0" foo.bind="bar"></first></template>')
export class Second {
  constructor() {
    this.visible = false;
    this.bar = { value: 'Hello' };
  }
  
  toggle() {
    this.visible = !this.visible;
  }
}
```

Regards
-- Reinhold

**Comment by jdanyow** [comment] 2015-10-15 11:13
@reinholdk thanks for the nice test case

@EisenbergEffect this is not fixed by https://github.com/aurelia/binding/commit/dfa8a4076a49e91411f9691d118a3c1cf4cd577e  ... looking into it

**Comment by jdanyow** [comment] 2015-10-15 11:20
@EisenbergEffect I'm going to be on the road most of the day today so won't have time to get a fix out for this but I think the issue is here:

https://github.com/aurelia/templating-resources/blob/master/src/if.js#L53

I believe `this.$parent` needs to be passed to the bind method

**Comment by EisenbergEffect** [comment] 2015-10-15 14:22
Hang out a few minutes and we'll have a new patch release out. Watch the main gitter channel. I'll make a quick announcement there once the new releases are available.

**Closed** 2015-10-15 14:21 UTC
