### ISSUE TITLE
splices[0].index from repeat.js:220 throws error in my app

### ISSUE THREAD

**Issue by capaj** [aurelia/templating-resources#35] opened 2015-04-13 01:13 UTC
This might be my mistake, but in case it isn't, could anyone have a look?

I have a simple twitter api app and I get one error each time my app bootsrapps. The repeat binding works, so the error doesn't break any functionality as far as I know, but it would be nicer, if it would not be throwing at all.

The repeat binding, which causes the error is here:
https://github.com/capaj/twitter-spelling-nazi/commit/c7b2b2535df7fc428ca5b0b2cc25166c9091c8d8#diff-473070e4d443c6b210157c10f9fa6f3bR15
 
Unfortunatelly, I don't have a callstack, as it is not shown in the console.
Also note that I use "github:aurelia/templating-resources@0.10.0".

**Comment by EisenbergEffect** [comment] 2015-04-13 01:25
@martingust Would you look into this please?

**Comment by stoffeastrom** [comment] 2015-04-15 20:19
I get the same error. It's because the `splices` has zero length. Also don't know if it's connected but now when I remove something from an array the referring element is reused which broke some stuff for me. I'm not sure that's the desired behavior?

**Comment by martingust** [comment] 2015-04-15 20:31
This issue should be fixed in #36. Regarding your other issue, can you please provide reproduction steps and I will take a look, thanks!

**Closed** 2015-04-16 13:55 UTC
Labels: bug

**Comment by stoffeastrom** [comment] 2015-04-16 20:16
@martingust Will do as soon as this get's in and I can reproduce it!
